name: Test and Release

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/sample.feature'
      - '**.md'
      - 'badges/**'
      - '.eslintignore'
      - '.github/linters/**'
      - '.gitignore'
      - '.gitattributes'
      - '.prettier*'
      - 'renovate.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    needs: [test]
    permissions:
      contents: write
      actions: write
      attestations: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@67139193614f5b9e8db87da1bd4240922b34d765
        id: changelog
        with:
          github-token: ${{ github.token }}
          output-file: 'CHANGELOG.md'
          skip-version-file: 'true'
          skip-commit: 'true'
          git-push: 'true'

      - name: Create Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        if: steps.changelog.outputs.tag != ''
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          token: ${{ github.token }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
